### PR TITLE
Speed up standards response

### LINKED ISSUE #220: The index request for standards seems to time out or is at least very slow
This became an issue during a call I just had for a demo when the app seemingly timeout / failed. I had to do a quick server restart. I was logged in at the time but I'm not sure if it's limited to that.

I suspect we need to do at least these two things:

- [ ] Majorly limit the relationships included in index requests. Include counts on the standard object (`skill_count`, `work_process_count`, etc.) where needed instead of the full lists.
- [ ] Add some caching

cc @jhash as this'll likely effect where he accesses some of this info on the front-end.

### PR DESCRIPTION
**Pull request by littleforest**
closes #220 

* Remove includes section from standards response
* Add caching

### CODE REVIEW

**Comment by littleforest** [comment]
@jhash here are the changes that remove the `includes` section and adds `work_processes_count`, `skills_count` to the occupation standard attributes. This should not be merged until your changes are added.

**Comment by jhash** [comment]
@littleforest I need an hours count. Currently I am summing this from all of the work processes.

**Comment by jhash** [comment]
@littleforest you also need to return the work processes and skills on the standard/:id GET within `included` still, looks like this strips them out completely.

**Comment by jhash** [comment]
@littleforest another thing, all of the skills_count and work_processes_count 's locally for me have the exact same count. I assume that is a bug since that's not true

**Comment by littleforest** [comment]
@jhash thanks for catching those issues.  Just pushed fixes for then all.

**Comment by jhash** [comment]
@littleforest this looks good, I had to change a few things to get the hours showing up properly on my end. Wouldn't have been working properly before either

**Comment by littleforest** [comment]
@jhash can you fix merge conflicts when you get a chance, thanks!

**Pull request merged**
